[protocol]
name = "Wormhole BNB Chain"
slug = "wormhole-bnb"
category = "bridge"
interface = "bridge"
chain = "bnb"
description = "Wormhole Portal bridge on BNB Chain"

[protocol.contracts]
token_bridge = "0xB6F6D86a8f9879A9c87f643768d9efc38c1Da6E7"
core = "0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B"
nft_bridge = "0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE"
