[protocol]
name = "Wormhole Polygon"
slug = "wormhole-polygon"
category = "bridge"
interface = "bridge"
chain = "polygon"
description = "Wormhole Portal bridge on Polygon"

[protocol.contracts]
token_bridge = "0x5a58505a96D1dbf8dF91cB21B54419FC36e93fdE"
core = "0x7A4B5a563CFEb71F59Ad09a4cFcF8d9f7B34D478"
nft_bridge = "0x90BBd86a6Fe93D3bc3ed6335935447E75fAb7fCf"
