[protocol]
name = "Wormhole Moonbeam"
slug = "wormhole-moonbeam"
category = "bridge"
interface = "bridge"
chain = "moonbeam"
description = "Wormhole Portal bridge on Moonbeam"

[protocol.contracts]
token_bridge = "0xb1731c586ca89a23809861c6103f0b96b3f57d92"
core = "0xC8e2b0cD52Cf01b0Ce87d389Daa3d414d4cE29f3"
nft_bridge = "0x453cfBe096C0f8D763E8C5F24B441097d577bdE2"
