[[token]]
symbol = "CELO"
name = "Celo"
address = "0x0000000000000000000000000000000000000000"
decimals = 18
tags = ["native"]

[[token]]
symbol = "WCELO"
name = "Wrapped CELO"
address = "0x471EcE3750Da237f93B8E339c536989b8978a438"
decimals = 18
tags = ["wrapped"]
[[token]]
symbol = "USDC"
name = "USD Coin"
address = "0xcebA9300f2b948710d2653dD7B07f33A8B32118C"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "USDT"
name = "Tether"
address = "0x48065fbBE25f71C9282ddf5e1cD6D6A887483D5e"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "WETH"
name = "Wrapped Ether"
address = "0x66803FB87aBd4aaC3cbB3fAd7C3aa01f6F3FB207"
decimals = 18
tags = ["wrapped"]
[[token]]
symbol = "WBTC"
name = "Wrapped Bitcoin"
address = "0xd71Ffd0940c920786eC4DbB5A12306669b5b81EF"
decimals = 8

[[token]]
symbol = "cUSD"
name = "Celo Dollar"
address = "0x765DE816845861e75A25fCA122bb6898B8B1282a"
decimals = 18
tags = ["stablecoin"]
