[protocol]
name = "FstSwap"
slug = "fstswap"
category = "dex"
interface = "uniswap_v2"
chain = "bnb"
native = false
description = "FstSwap on BNB ($13M TVL)"
[protocol.contracts]
router = "0xb3ca4d73b1e0ea2c53b42173388cc01e1c226f40"
factory = "0x9A272d734c5a0d7d84E0a892e891a553e8066dce"
