[protocol]
name = "Kim Exchange Mode"
slug = "kim-mode"
category = "dex"
interface = "solidly_cl"
chain = "mode"
native = true
description = "Kim Exchange — Algebra Integral concentrated liquidity DEX on Mode"

[protocol.contracts]
router = "0xAc48FcF1049668B285f3dC72483DF5Ae2162f7e8"
factory = "0xB5F00c2C5f8821155D8ed27E31932CFD9DB3C5D5"
