[protocol]
name = "SushiSwap Scroll"
slug = "sushiswap-scroll"
category = "dex"
interface = "uniswap_v2"
chain = "scroll"
native = false
description = "SushiSwap V2 on Scroll"

[protocol.contracts]
router = "0x9B3336186a38E1b6c21955d112dbb0343Ee061eE"
factory = "0xB45e53277a7e0F1D35f2a77160e91e25507f1763"
