[protocol]
name = "SushiSwap V3 Gnosis"
slug = "sushiswap-v3-gnosis"
category = "dex"
interface = "uniswap_v3"
chain = "gnosis"
native = false
description = "SushiSwap V3 on Gnosis Chain"

[protocol.contracts]
router = "0x4F54dd2F4f30347d841b7783aD08c050d8410a9d"
factory = "0xf78031CBCA409F2FB6876BDFDBc1b2df24cF9bEf"
