[protocol]
name = "SushiSwap V3 Kava"
slug = "sushiswap-v3-kava"
category = "dex"
interface = "uniswap_v3"
chain = "kava"
native = false
description = "SushiSwap V3 on Kava"

[protocol.contracts]
router = "0xFF51a7C624Eb866917102707F3dA8bFb99Db8692"
factory = "0x1e9B24073183d5c6B7aE5FB4b8f0b1dd83FDC77a"
