[protocol]
name = "Uniswap V2 Optimism"
slug = "uniswap-v2-op"
category = "dex"
interface = "uniswap_v2"
chain = "optimism"
native = false
description = "Uniswap V2 on Optimism"

[protocol.contracts]
router = "0x4A7b5Da61326A6379179b40d00F57E5bbDC962c2"
factory = "0x0c3c1c532F1e39EdF36BE9Fe0bE1410313E074Bf"
