[protocol]
name = "Uniswap V3 Avalanche"
slug = "uniswap-v3-avax"
category = "dex"
interface = "uniswap_v3"
chain = "avalanche"
native = false
description = "Uniswap V3 on Avalanche C-Chain"

[protocol.contracts]
router = "0xbb00FF08d01D300023C629E8fFfFcb65A5a578cE"
factory = "0x740b1c1de25031C31FF4fC9A62f554A55cdC1baD"
quoter = "0xbe0F5544EC67e9B3b2D979aaA43f18Fd87E6257F"
