[protocol]
name = "Uniswap V2 World Chain"
slug = "uniswap-v2-worldchain"
category = "dex"
interface = "uniswap_v2"
chain = "worldchain"
native = false
description = "Uniswap V2 on World Chain"

[protocol.contracts]
router = "0x541aB7c31A119441eF3575F6973277DE0eF460bd"
factory = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
