[protocol]
name = "Aave V3 Arbitrum"
slug = "aave-v3-arb"
category = "lending"
interface = "aave_v3"
chain = "arbitrum"
native = false
description = "Aave V3 on Arbitrum One"

[protocol.contracts]
pool = "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
pool_addresses_provider = "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb"
oracle = "0xb56c2F0B653B2e0b10C9b928C8580Ac5Df02C7C7"
pool_data_provider = "0x69FA688f1Dc47d4B5d8029D5a35FB7a548310654"
