[protocol]
name = "Aave V3 Optimism"
slug = "aave-v3-op"
category = "lending"
interface = "aave_v3"
chain = "optimism"
native = false
description = "Aave V3 on Optimism"

[protocol.contracts]
pool = "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
pool_addresses_provider = "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb"
oracle = "0xD81eb3728a631871a7eBBaD631b5f424909f0c77"
pool_data_provider = "0x243Aa95cAC2a25651eda86e80bEe66114413c43b"
