[protocol]
name = "Aave V3 Base"
slug = "aave-v3-base"
category = "lending"
interface = "aave_v3"
chain = "base"
native = false
description = "Aave V3 on Base"

[protocol.contracts]
pool = "0xA238Dd80C259a72e81d7e4664a9801593F98d1c5"
pool_addresses_provider = "0xe20fCBdBfFC4Dd138cE8b2E6FBb6CB49777ad64D"
oracle = "0x2Cc0Fc26eD4563A5ce5e8bdcfe1A2878676Ae156"
pool_data_provider = "0x2d8A3C5677189723C4cB8873CfC9C8976FDF38Ac"
