[protocol]
name = "Aave V3 Avalanche"
slug = "aave-v3-avax"
category = "lending"
interface = "aave_v3"
chain = "avalanche"
native = false
description = "Aave V3 on Avalanche C-Chain"

[protocol.contracts]
pool = "0x794a61358D6845594F94dc1DB02A252b5b4814aD"
pool_addresses_provider = "0xa97684ead0e402dC232d5A977953DF7ECBaB3CDb"
oracle = "0xEBd36016B3eD09D4693Ed4251c67Bd858c3c7C9C"
pool_data_provider = "0x243Aa95cAC2a25651eda86e80bEe66114413c43b"
