[protocol]
name = "PrimeFi"
slug = "primefi-hyperevm"
category = "lending"
interface = "aave_v2"
chain = "hyperevm"
native = false
description = "PrimeFi lending on HyperEVM"

[protocol.contracts]
pool = "0xb339448E13E273f6F46e3390e0932Ab7fF9F113F"
pool_addresses_provider = "0x07093ca1e6c8c03ff77dea07532f738d88de1d75"
oracle = "0x8bd82c5f94d2caff3f980f0137f16add71e98dfb"
