[protocol]
name = "Convex Finance Arbitrum"
slug = "convex-arbitrum"
category = "vault"
interface = "erc4626"
chain = "arbitrum"
native = false
description = "Convex Finance Booster on Arbitrum One"

[protocol.contracts]
booster = "0xF403C135812408BFbE8713b5A23a04b3D48AAE31"
