[[token]]
symbol = "ETH"
name = "Ether"
address = "0x0000000000000000000000000000000000000000"
decimals = 18
tags = ["native"]

[[token]]
symbol = "WETH"
name = "Wrapped Ether"
address = "0xC9BdeEd33CD01541e1eeD10f90519d2C06Fe3feB"
decimals = 18
is_native_wrapper = true
tags = ["wrapped"]

[[token]]
symbol = "USDC"
name = "USD Coin"
address = "0xB12BFcA5A55806AaF64E99521918A4bf0fC40802"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "USDT"
name = "Tether USD"
address = "0x4988a896b1227218e4A686fdE5EabdcAbd91571f"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "AURORA"
name = "Aurora"
address = "0x8BEc47865aDe3B172A928df8f990Bc7f2A3b9f79"
decimals = 18
tags = ["governance"]
