[[token]]
symbol = "ETH"
name = "Ether"
address = "0x0000000000000000000000000000000000000000"
decimals = 18
tags = ["native"]

[[token]]
symbol = "WETH"
name = "Wrapped Ether"
address = "0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000"
decimals = 18
is_native_wrapper = true
tags = ["wrapped"]

[[token]]
symbol = "USDC"
name = "USD Coin"
address = "0x66a2A913e447d6b4BF33EFbec43aAeF87890FBbc"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "USDT"
name = "Tether USD"
address = "0x5DE1677344D3Cb0D7D465c10b72A8f60699C062d"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "BOBA"
name = "Boba Token"
address = "0xa18bF3994C0Cc6E3b63ac420308E5383f53120D7"
decimals = 18
tags = ["governance"]
