[[token]]
symbol = "MON"
name = "Monad"
address = "0x0000000000000000000000000000000000000000"
decimals = 18
tags = ["native"]

[[token]]
symbol = "WMON"
name = "Wrapped MON"
address = "0x3bd359C1119dA7Da1D913D1C4D2B7c461115433A"
decimals = 18
tags = ["wrapped"]

[[token]]
symbol = "USDC"
name = "USD Coin"
address = "0x754704Bc059F8C67012fEd69BC8A327a5aafb603"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "USDT0"
name = "USDT0"
address = "0xe7cd86e13AC4309349F30B3435a9d337750fC82D"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "WETH"
name = "Wrapped Ether"
address = "0xEE8c0E9f1BFFb4Eb878d8f15f368A02a35481242"
decimals = 18
tags = ["wrapped"]

[[token]]
symbol = "WBTC"
name = "Wrapped BTC"
address = "0x0555E30da8f98308EdB960aa94C0Db47230d2B9c"
decimals = 8
tags = ["wrapped"]

[[token]]
symbol = "wstETH"
name = "Wrapped stETH"
address = "0x10Aeaf63194db8d453d4D85a06E5eFE1dd0b5417"
decimals = 18
tags = ["wrapped"]
