[[token]]
symbol = "ETH"
name = "Ether"
address = "0x0000000000000000000000000000000000000000"
decimals = 18
tags = ["native"]

[[token]]
symbol = "WETH"
name = "Wrapped Ether"
address = "0x4200000000000000000000000000000000000006"
decimals = 18
is_native_wrapper = true
tags = ["wrapped"]

[[token]]
symbol = "USDC"
name = "USD Coin"
address = "0xbA9986D2381edf1DA03B0B9c1f8b00dc4AacC9B1"
decimals = 6
tags = ["stablecoin"]

[[token]]
symbol = "USDT"
name = "Tether USD"
address = "0xf067133EA4e68B5E15f04F80c1AFF0A5B2F97D8b"
decimals = 6
tags = ["stablecoin"]
