[protocol]
name = "Wormhole Gnosis"
slug = "wormhole-gnosis"
category = "bridge"
interface = "bridge"
chain = "gnosis"
description = "Wormhole Portal bridge on Gnosis Chain"

[protocol.contracts]
token_bridge = "0xBa631b6C69b0D382e0893A5C432F56DEbC9Bc7CF"
core = "0xbebdb6C8ddC678FfA9f8748f85C815C556Dd8ac6"
