[protocol]
name = "Wormhole Ethereum"
slug = "wormhole-ethereum"
category = "bridge"
interface = "bridge"
chain = "ethereum"
description = "Wormhole Portal bridge on Ethereum"

[protocol.contracts]
token_bridge = "0x3ee18B2214AFF97000D974cf647E7C347E8fa585"
core = "0x98f3c9e6E3fAce36bAAd05FE09d375Ef1464288B"
nft_bridge = "0x6FFd7EdE62328b3Af38FCD61461Bbfc52F5651fE"
