[protocol]
name = "Wormhole Arbitrum"
slug = "wormhole-arbitrum"
category = "bridge"
interface = "bridge"
chain = "arbitrum"
description = "Wormhole Portal bridge on Arbitrum One"

[protocol.contracts]
token_bridge = "0x0b2402144Bb366A632D14B83F244D2e0e21bD39c"
core = "0xa5f208e072434bC67592E4C49C1B991BA79BCA46"
nft_bridge = "0x3dD14D553cFD986EAC8e3bddF629d82073e188c8"
