[protocol]
name = "Wormhole Avalanche"
slug = "wormhole-avalanche"
category = "bridge"
interface = "bridge"
chain = "avalanche"
description = "Wormhole Portal bridge on Avalanche C-Chain"

[protocol.contracts]
token_bridge = "0x0e082F06FF657D94310cB8cE8B0D9a04541d8052"
core = "0x54a8e5f9c4CbA08F9943965859F6c34eAF03E26c"
nft_bridge = "0xf7B6737Ca9c4e08aE573F75A97B73D7a813f5De5"
