import type { Command } from "commander";
import pc from "picocolors";
import { createInterface } from "readline";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";

const DEFI_DIR = resolve(process.env.HOME || "~", ".defi");
const ENV_FILE = resolve(DEFI_DIR, ".env");

// ── .env helpers ──────────────────────────────────────────────

function ensureDefiDir() {
  if (!existsSync(DEFI_DIR)) mkdirSync(DEFI_DIR, { recursive: true, mode: 0o700 });
}

function loadEnvFile(): Record<string, string> {
  if (!existsSync(ENV_FILE)) return {};
  const lines = readFileSync(ENV_FILE, "utf-8").split("\n");
  const env: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx > 0) {
      env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
    }
  }
  return env;
}

function writeEnvFile(env: Record<string, string>) {
  ensureDefiDir();
  const lines = [
    "# defi-cli configuration",
    "# Generated by 'defi setup' — edit freely",
    "",
  ];
  for (const [key, value] of Object.entries(env)) {
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  writeFileSync(ENV_FILE, lines.join("\n"), { mode: 0o600 });
}

// ── Interactive helpers ────────────────────────────────────────

function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((res) => rl.question(question, (answer) => res(answer.trim())));
}

// ── Validation helpers ─────────────────────────────────────────

function isValidAddress(s: string): boolean {
  return /^0x[0-9a-fA-F]{40}$/.test(s);
}

function isValidPrivateKey(s: string): boolean {
  return /^0x[0-9a-fA-F]{64}$/.test(s);
}

async function deriveAddress(privateKey: string): Promise<string | null> {
  try {
    const { privateKeyToAccount } = await import("viem/accounts");
    const account = privateKeyToAccount(privateKey as `0x${string}`);
    return account.address;
  } catch {
    return null;
  }
}

// ── Command ────────────────────────────────────────────────────

export function registerSetup(program: Command) {
  program
    .command("setup")
    .alias("init")
    .description("Interactive setup wizard — configure wallet & RPC URLs")
    .action(async () => {
      const rl = createInterface({ input: process.stdin, output: process.stdout });

      try {
        console.log(pc.cyan(pc.bold("\n  defi-cli Setup Wizard\n")));

        // Show current config if it exists
        const existing = loadEnvFile();
        if (Object.keys(existing).length > 0) {
          console.log(pc.white("  Current configuration:"));
          for (const [key, value] of Object.entries(existing)) {
            const masked =
              key.toLowerCase().includes("key")
                ? value.slice(0, 6) + "..." + value.slice(-4)
                : value;
            console.log(`    ${pc.cyan(key.padEnd(24))} ${pc.gray(masked)}`);
          }
          console.log();
          const overwrite = await ask(rl, "  Overwrite existing config? (y/N): ");
          if (overwrite.toLowerCase() !== "y" && overwrite.toLowerCase() !== "yes") {
            console.log(pc.gray("\n  Keeping existing configuration.\n"));
            rl.close();
            return;
          }
          console.log();
        }

        const newEnv: Record<string, string> = {};

        // ── Wallet address / private key ──
        console.log(pc.cyan(pc.bold("  Wallet")));

        const privateKey = await ask(rl, "  Private key (optional, for --broadcast, 0x...): ");
        if (privateKey) {
          const normalized = privateKey.startsWith("0x") ? privateKey : `0x${privateKey}`;
          if (!isValidPrivateKey(normalized)) {
            console.log(pc.red("  Invalid private key (must be 0x + 64 hex chars). Skipped."));
          } else {
            newEnv.DEFI_PRIVATE_KEY = normalized;
            const derived = await deriveAddress(normalized);
            if (derived) {
              newEnv.DEFI_WALLET_ADDRESS = derived;
              console.log(`  ${pc.green("OK")} derived address: ${pc.gray(derived)}`);
            }
          }
        }

        if (!newEnv.DEFI_WALLET_ADDRESS) {
          const address = await ask(rl, "  Wallet address (0x...): ");
          if (address) {
            if (!isValidAddress(address)) {
              console.log(pc.yellow("  Invalid address format. Skipping."));
            } else {
              newEnv.DEFI_WALLET_ADDRESS = address;
              console.log(`  ${pc.green("OK")} ${pc.gray(address)}`);
            }
          }
        }

        // ── RPC URLs ──
        console.log(pc.cyan(pc.bold("\n  RPC URLs")) + pc.gray(" (press Enter to use public defaults)"));

        const hyperevmRpc = await ask(rl, "  HyperEVM RPC URL: ");
        if (hyperevmRpc) {
          newEnv.HYPEREVM_RPC_URL = hyperevmRpc;
          console.log(`  ${pc.green("OK")} HyperEVM RPC set`);
        }

        const mantleRpc = await ask(rl, "  Mantle RPC URL: ");
        if (mantleRpc) {
          newEnv.MANTLE_RPC_URL = mantleRpc;
          console.log(`  ${pc.green("OK")} Mantle RPC set`);
        }

        // Merge with existing non-overwritten keys (keep old keys not touched above)
        const finalEnv = { ...existing, ...newEnv };

        // Write .env
        writeEnvFile(finalEnv);

        // Summary
        console.log(pc.cyan(pc.bold("\n  Setup Complete!\n")));
        console.log(`  Config:  ${pc.gray(ENV_FILE)}`);
        if (finalEnv.DEFI_WALLET_ADDRESS) {
          console.log(`  Wallet:  ${pc.gray(finalEnv.DEFI_WALLET_ADDRESS)}`);
        }
        if (finalEnv.DEFI_PRIVATE_KEY) {
          console.log(`  Key:     ${pc.green("configured")}`);
        }
        if (finalEnv.HYPEREVM_RPC_URL) {
          console.log(`  HyperEVM RPC: ${pc.gray(finalEnv.HYPEREVM_RPC_URL)}`);
        }
        if (finalEnv.MANTLE_RPC_URL) {
          console.log(`  Mantle RPC:   ${pc.gray(finalEnv.MANTLE_RPC_URL)}`);
        }

        console.log(pc.bold(pc.white("\n  Next steps:")));
        console.log(`    ${pc.green("defi portfolio")}          view balances & positions`);
        console.log(`    ${pc.green("defi scan")}               scan for exploits`);
        console.log(`    ${pc.green("defi dex quote")}          get a swap quote`);
        console.log(`    ${pc.green("defi --help")}             browse all commands\n`);

        rl.close();
      } catch (err) {
        rl.close();
        throw err;
      }
    });
}
