import type { Command } from "commander";
import pc from "picocolors";
import { createInterface } from "readline";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import { resolve } from "path";
import { homedir } from "os";

// homedir() handles HOME unset / Windows USERPROFILE / etc.
// Previous resolve(process.env.HOME || "~", ".defi") wrote to literal `~/.defi`
// inside cwd when HOME was unset (e.g. in some sandboxed CI runners).
const DEFI_DIR = resolve(homedir(), ".defi");
const ENV_FILE = resolve(DEFI_DIR, ".env");

// ── .env helpers ──────────────────────────────────────────────

function ensureDefiDir() {
  if (!existsSync(DEFI_DIR)) mkdirSync(DEFI_DIR, { recursive: true, mode: 0o700 });
}

function loadEnvFile(): Record<string, string> {
  if (!existsSync(ENV_FILE)) return {};
  const lines = readFileSync(ENV_FILE, "utf-8").split("\n");
  const env: Record<string, string> = {};
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx > 0) {
      env[trimmed.slice(0, eqIdx)] = trimmed.slice(eqIdx + 1);
    }
  }
  return env;
}

function writeEnvFile(env: Record<string, string>) {
  ensureDefiDir();
  const lines = [
    "# defi-cli configuration",
    "# Generated by 'defi setup' — edit freely",
    "",
  ];
  for (const [key, value] of Object.entries(env)) {
    lines.push(`${key}=${value}`);
  }
  lines.push("");
  writeFileSync(ENV_FILE, lines.join("\n"), { mode: 0o600 });
}

// ── Interactive helpers ────────────────────────────────────────

function ask(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  return new Promise((res) => rl.question(question, (answer) => res(answer.trim())));
}

/**
 * Read sensitive input (private key) without echoing it to the terminal.
 * Falls back to a plain question() when stdin is not a TTY (e.g. piped CI
 * input) — there's no terminal to disable echo on, but the input also isn't
 * being shown to a human in that case.
 */
function askSecret(rl: ReturnType<typeof createInterface>, question: string): Promise<string> {
  const stdin = process.stdin;
  if (!stdin.isTTY) return ask(rl, question);
  process.stdout.write(question);
  // Toggle the readline output so each keypress doesn't appear in the terminal.
  // Approach: temporarily replace rl.output's write with a no-op while reading.
  const rlAny = rl as unknown as { _writeToOutput?: (s: string) => void };
  const original = rlAny._writeToOutput;
  rlAny._writeToOutput = (s: string) => {
    // Allow newline (Enter) and ANSI control sequences through; suppress
    // visible characters of the secret itself.
    if (s.includes("\n") || s.includes("\r")) {
      original?.call(rl, s);
    }
  };
  return new Promise((res) => {
    rl.question("", (answer) => {
      rlAny._writeToOutput = original;
      process.stdout.write("\n"); // Newline since echo was suppressed.
      res(answer.trim());
    });
  });
}

/**
 * Mask the path of an RPC URL so embedded API keys (e.g.
 * https://eth.example.com/v3/abc123) don't end up echoed back in the
 * "Current configuration" or "Setup Complete" summary panes.
 */
function maskRpcUrl(s: string): string {
  try {
    const u = new URL(s);
    if (u.pathname && u.pathname !== "/" && u.pathname.length > 1) {
      return `${u.protocol}//${u.host}/***`;
    }
    return `${u.protocol}//${u.host}`;
  } catch {
    return "***";
  }
}

function isValidRpcUrl(s: string): boolean {
  try {
    const u = new URL(s);
    // Accept http(s) only — viem transports across the CLI hardcode `http(url)`,
    // so a stored ws:// URL would parse cleanly here but fail at the first
    // RPC call with "unknown scheme". Better to reject it during setup.
    return u.protocol === "http:" || u.protocol === "https:";
  } catch {
    return false;
  }
}

// ── Validation helpers ─────────────────────────────────────────

function isValidAddress(s: string): boolean {
  return /^0x[0-9a-fA-F]{40}$/.test(s);
}

function isValidPrivateKey(s: string): boolean {
  return /^0x[0-9a-fA-F]{64}$/.test(s);
}

async function deriveAddress(privateKey: string): Promise<string | null> {
  try {
    const { privateKeyToAccount } = await import("viem/accounts");
    const account = privateKeyToAccount(privateKey as `0x${string}`);
    return account.address;
  } catch {
    return null;
  }
}

// ── Command ────────────────────────────────────────────────────

export function registerSetup(program: Command) {
  program
    .command("setup")
    .alias("init")
    .description("Interactive setup wizard — configure wallet & RPC URLs")
    .action(async () => {
      const rl = createInterface({ input: process.stdin, output: process.stdout });

      try {
        console.log(pc.cyan(pc.bold("\n  defi-cli Setup Wizard\n")));

        // Show current config if it exists
        const existing = loadEnvFile();
        if (Object.keys(existing).length > 0) {
          console.log(pc.white("  Current configuration:"));
          for (const [key, value] of Object.entries(existing)) {
            // Always mask private keys; mask RPC URL paths because providers
            // commonly embed API keys in the path component.
            let masked: string;
            if (key.toLowerCase().includes("key")) {
              masked = value.slice(0, 6) + "..." + value.slice(-4);
            } else if (key.endsWith("RPC_URL")) {
              masked = maskRpcUrl(value);
            } else {
              masked = value;
            }
            console.log(`    ${pc.cyan(key.padEnd(24))} ${pc.gray(masked)}`);
          }
          console.log();
          const overwrite = await ask(rl, "  Overwrite existing config? (y/N): ");
          if (overwrite.toLowerCase() !== "y" && overwrite.toLowerCase() !== "yes") {
            console.log(pc.gray("\n  Keeping existing configuration.\n"));
            rl.close();
            return;
          }
          console.log();
        }

        const newEnv: Record<string, string> = {};

        // ── Wallet address / private key ──
        console.log(pc.cyan(pc.bold("  Wallet")));

        // Hidden input: characters are suppressed in the terminal so the key
        // doesn't end up in shoulder-surfing distance / terminal scrollback.
        const privateKey = await askSecret(rl, "  Private key (optional, for --broadcast, 0x... — input hidden): ");
        if (privateKey) {
          const normalized = privateKey.startsWith("0x") ? privateKey : `0x${privateKey}`;
          if (!isValidPrivateKey(normalized)) {
            console.log(pc.red("  Invalid private key (must be 0x + 64 hex chars). Skipped."));
          } else {
            newEnv.DEFI_PRIVATE_KEY = normalized;
            const derived = await deriveAddress(normalized);
            if (derived) {
              newEnv.DEFI_WALLET_ADDRESS = derived;
              console.log(`  ${pc.green("OK")} derived address: ${pc.gray(derived)}`);
            }
          }
        }

        if (!newEnv.DEFI_WALLET_ADDRESS) {
          const address = await ask(rl, "  Wallet address (0x...): ");
          if (address) {
            if (!isValidAddress(address)) {
              console.log(pc.yellow("  Invalid address format. Skipping."));
            } else {
              newEnv.DEFI_WALLET_ADDRESS = address;
              console.log(`  ${pc.green("OK")} ${pc.gray(address)}`);
            }
          }
        }

        // ── RPC URLs ──
        console.log(pc.cyan(pc.bold("\n  RPC URLs")) + pc.gray(" (press Enter to use public defaults)"));

        const rpcPrompts: Array<{ env: string; label: string }> = [
          { env: "HYPEREVM_RPC_URL", label: "HyperEVM" },
          { env: "MANTLE_RPC_URL",   label: "Mantle" },
          { env: "BASE_RPC_URL",     label: "Base" },
          { env: "BNB_RPC_URL",      label: "BNB" },
          { env: "MONAD_RPC_URL",    label: "Monad" },
        ];
        for (const { env, label } of rpcPrompts) {
          const value = await ask(rl, `  ${label} RPC URL: `);
          if (value) {
            // Reject obvious typos / wrong protocols up front rather than
            // letting them fail at the first eth_call hours later.
            if (!isValidRpcUrl(value)) {
              console.log(pc.yellow(`  Invalid URL (${value}). Skipped — re-run setup to retry.`));
              continue;
            }
            newEnv[env] = value;
            console.log(`  ${pc.green("OK")} ${label} RPC set`);
          }
        }

        // Merge with existing non-overwritten keys (keep old keys not touched above)
        const finalEnv = { ...existing, ...newEnv };

        // Write .env
        writeEnvFile(finalEnv);

        // Summary
        console.log(pc.cyan(pc.bold("\n  Setup Complete!\n")));
        console.log(`  Config:  ${pc.gray(ENV_FILE)}`);
        if (finalEnv.DEFI_WALLET_ADDRESS) {
          console.log(`  Wallet:  ${pc.gray(finalEnv.DEFI_WALLET_ADDRESS)}`);
        }
        if (finalEnv.DEFI_PRIVATE_KEY) {
          console.log(`  Key:     ${pc.green("configured")}`);
        }
        const rpcSummary: Array<[string, string]> = [
          ["HYPEREVM_RPC_URL", "HyperEVM RPC"],
          ["MANTLE_RPC_URL",   "Mantle RPC  "],
          ["BASE_RPC_URL",     "Base RPC    "],
          ["BNB_RPC_URL",      "BNB RPC     "],
          ["MONAD_RPC_URL",    "Monad RPC   "],
        ];
        for (const [k, label] of rpcSummary) {
          const v = finalEnv[k];
          if (v) console.log(`  ${label}: ${pc.gray(maskRpcUrl(v))}`);
        }

        console.log(pc.bold(pc.white("\n  Next steps:")));
        console.log(`    ${pc.green("defi portfolio")}          view balances & positions`);
        console.log(`    ${pc.green("defi scan")}               scan for exploits`);
        console.log(`    ${pc.green("defi dex quote")}          get a swap quote`);
        console.log(`    ${pc.green("defi --help")}             browse all commands\n`);

        rl.close();
      } catch (err) {
        rl.close();
        throw err;
      }
    });
}
