[protocol]
name = "BakerySwap"
slug = "bakeryswap"
category = "dex"
interface = "uniswap_v2"
chain = "bnb"
native = false
description = "BakerySwap on BNB ($4M TVL)"
[protocol.contracts]
router = "0xCDe540d7eAFE93AC5fE6233Bee57E1270D3E330F"
factory = "0x01bF7C66c6BD861915CdaaE475042d3c4BaE16A7"
