[protocol]
name = "Curve Optimism"
slug = "curve-optimism"
category = "dex"
interface = "curve_stableswap"
chain = "optimism"
native = false
description = "Curve StableSwap-NG on Optimism"

[protocol.contracts]
factory = "0x5eeE3091f747E60a045a2E715a4c71e600e31F6E"
router = "0x0DCDED3545D565bA3B19E683431381007245d983"
