[protocol]
name = "Curve Fantom"
slug = "curve-fantom"
category = "dex"
interface = "curve_stableswap"
chain = "fantom"
native = false
description = "Curve StableSwap-NG on Fantom"

[protocol.contracts]
factory = "0xe61Fb97Ef6eBFBa12B36Ffd7be785c1F5A2DE66b"
