[protocol]
name = "Merchant Moe Mantle"
slug = "merchantmoe-mantle"
category = "dex"
interface = "uniswap_v2"
chain = "mantle"
native = false
description = "Merchant Moe on Mantle"

[protocol.contracts]
router = "0xeaEE7EE68874218c3558b40063c42B82D3E7232a"
factory = "0x5bEf015CA9424A7C07B68490616a4C1F094BEdEc"
