[protocol]
name = "Uniswap V3 Soneium"
slug = "uniswap-v3-soneium"
category = "dex"
interface = "uniswap_v3"
chain = "soneium"
native = false
description = "Uniswap V3 on Soneium"

[protocol.contracts]
router = "0x0dC73Fe1341365929Ed8a89Dd47097A9FDD254D0"
factory = "0x137841043180BBA8EF52828F9030D1b7fE065F95"
