[protocol]
name = "Uniswap V2 Polygon"
slug = "uniswap-v2-polygon"
category = "dex"
interface = "uniswap_v2"
chain = "polygon"
native = false
description = "Uniswap V2 on Polygon"

[protocol.contracts]
router = "0xedf6066a2b290C185783862C7F4776A2C8077AD1"
factory = "0x9e5A52f57b3038F1B8EeE45F28b3C1967e22799C"
