[protocol]
name = "Uniswap V3 Blast"
slug = "uniswap-v3-blast"
category = "dex"
interface = "uniswap_v3"
chain = "blast"
native = false
description = "Uniswap V3 on Blast"

[protocol.contracts]
router = "0x549FEB8c9bd4c12Ad2AB27022dA12492aC452B66"
factory = "0x792edAdE80af5fC680d96a2eD80A44247D2Cf6Fd"
quoter = "0x6Cdcd65e03c1CEc3730AeeCd45bc140D57A25C77"
position_manager = "0xB218e4f7cF0533d4696fDfC419A0023D33345F28"
